Select LEFT(TENNV,1) AS FIRSTLETTER FROM NHANVIEN


SELECT CONVERT(DATE, GETDATE())

SELECT DATENAME(YEAR, GETDATE()) AS YEAR,
	DATENAME(WEEK, GETDATE()) AS WEEK,
	DATENAME(DAYOFYEAR, GETDATE()) AS DAYOFYEAR,
	DATENAME(MONTH, GETDATE()) AS MONTH,
	DATENAME(DAY, GETDATE()) AS DAY

----
SELECT * FROM PHANCONG

SELECT MA_NVIEN, MADA, STT,
	CAST(THOIGIAN AS DECIMAL(5,1)) AS 'Thoi Gian' 
FROM PHANCONG
---
SELECT MA_NVIEN, MADA, STT,
	CONVERT (DECIMAL(5,1), THOIGIAN) AS 'Thoi Gian' 
FROM PHANCONG
--- LIET KE TEN DE AN VA TONG THOI GIAN LAM VIEC CUA TAT CA NHAN VIEN TRONG DE AN 
SELECT * FROM DEAN
SELECT * FROM NHANVIEN
SELECT * FROM PHANCONG

SELECT d.TENDEAN,CAST(SUM(p.THOIGIAN) AS VARCHAR(15)) AS 'TONG THOI GIAN'
FROM DEAN d 
JOIN PHANCONG p
ON d.MADA = p.MADA 
GROUP BY d.TENDEAN
ORDER BY SUM(p.THOIGIAN) ASC

--- LIET KE TEN PHONG BAN VA LUONG TRUNG BINH CUA NHUNG NHAN VIEN TRONG PHONG BAN DO 

SELECT * FROM PHONGBAN
SELECT * FROM NHANVIEN


SELECT p.TENPHG, ROUND(AVG(n.LUONG),2) AS 'Luong Trung Binh'
FROM PHONGBAN p
JOIN NHANVIEN n 
ON p.MAPHG = n.PHG 
GROUP BY p.TENPHG
--OR--
SELECT p.TENPHG, CONVERT(DECIMAL(15,2),AVG(n.LUONG)) AS 'Luong Trung Binh'
FROM PHONGBAN p
JOIN NHANVIEN n 
ON p.MAPHG = n.PHG 
GROUP BY p.TENPHG
--OR--
SELECT p.TENPHG, FORMAT(CONVERT(DECIMAL(15,2),AVG(n.LUONG)), 'N', 'vi-vn') AS 'Luong Trung Binh'
FROM PHONGBAN p
JOIN NHANVIEN n 
ON p.MAPHG = n.PHG 
GROUP BY p.TENPHG
--OR--
SELECT p.TENPHG, CONVERT(VARCHAR(15),CAST(AVG(n.LUONG) AS MONEY),1) AS 'Luong Trung Binh'
FROM PHONGBAN p
JOIN NHANVIEN n 
ON p.MAPHG = n.PHG 
GROUP BY p.TENPHG
----LIET KE TEN DE AN , TONG SO GIO LAM VIEC MOT TUAN CUA TAT CA NHAN VIEN TRONG DE AN DO
SELECT * FROM DEAN
SELECT * FROM PHANCONG

SELECT d.TENDEAN, CEILING(SUM(p.THOIGIAN)) AS 'TONG GIO LAM VIEC - CEILING',
	ROUND(SUM(p.THOIGIAN),2) AS 'TONG GIO LAM VIEC - ROUND',
	FLOOR(SUM(p.THOIGIAN)) AS 'TONG GIO LAM VIEC-FLOOR'
FROM DEAN d 
INNER JOIN PHANCONG p
ON d.MADA = p.MADA
GROUP BY d.TENDEAN
--OR--
SELECT d.TENDEAN, CEILING(SUM(p.THOIGIAN)) AS 'TONG GIO LAM VIEC - CEILING',
	ROUND(SUM(p.THOIGIAN),2) AS 'TONG GIO LAM VIEC - ROUND',
	FLOOR(SUM(p.THOIGIAN)) AS 'TONG GIO LAM VIEC-FLOOR'
FROM DEAN d 
RIGHT JOIN PHANCONG p
ON d.MADA = p.MADA
GROUP BY d.TENDEAN
---IN HO TEN CUA NHAN VIEN CO LUONG THANG > TRUNG BINH PHONG NGHIEN CUU
SELECT * FROM PHONGBAN
SELECT * FROM NHANVIEN

DECLARE @AVG FLOAT
SELECT @AVG = AVG(LUONG) FROM NHANVIEN
WHERE PHG = 5

SELECT CONCAT(HONV, ' ',TENLOT, ' ', TENNV) FROM NHANVIEN
WHERE LUONG > @AVG	

----dsach nhan vien co tren 2 nhan than , hien thi ten duong 
SELECT * FROM THANNHAN
SELECT * FROM NHANVIEN



SELECT UPPER(n.HONV),
	LOWER(n.TENLOT),
	LOWER(LEFT(n.TENNV,1)),
	UPPER(SUBSTRING(TENNV,2,1)),
	SUBSTRING(TENNV,3,LEN(TENNV)),
	CHARINDEX(' ', DCHI),
	CHARINDEX(',', DCHI),
	SUBSTRING(DCHI, CHARINDEX(' ', DCHI),CHARINDEX(',', DCHI)-CHARINDEX(' ', DCHI))
FROM NHANVIEN n
 WHERE n.MANV  IN (
SELECT  t.MA_NVIEN FROM THANNHAN t
GROUP BY t.MA_NVIEN
HAVING COUNT(t.MA_NVIEN) > 2)
----cho biet ten phong ban, ho ten truong phong ban co dong nhan vien nhat	
-- hien thi them cot thay the ten truong phong ban la 'fpoly'
SELECT * FROM PHONGBAN
SELECT * FROM NHANVIEN


	DECLARE @ThongKe table (PHG int, TK int)
	DECLARE @MAX INT 

	INSERT INTO @ThongKe SELECT  PHG, COUNT(MANV)  FROM NHANVIEN 
	GROUP BY PHG

	SELECT  @MAX = MAX(TK) FROM @ThongKe

	SELECT p.TENPHG, CONCAT(n.HONV,' ', n.TENLOT,' ', n.TENNV) AS 'Ten Truong Phong',
		CONCAT(n.HONV,' ', n.TENLOT,' ', 'Fpoly') AS 'Ten THAY DOI'
	FROM NHANVIEN n
	JOIN PHONGBAN p
	ON n.MANV = p.TRPHG
	WHERE n.PHG = @MAX



