USE QLDA;
--- CHO BIET NHAN VIEN CO SINH NAM 1960 -> 1965
SELECT * FROM NHANVIEN
WHERE DATENAME(YEAR, NGSINH) BETWEEN 1960 AND 1965;
--- TINH TUOI CUA TAT CA NHAN VIEN
SELECT *, DATEDIFF(YEAR, NGSINH, GETDATE()) AS AGE FROM NHANVIEN;
---- DUA VAO NGAY SINH CHO BIET NHAN VIEN SINH VAO THU MAY 
SELECT *, DATENAME(WEEKDAY, NGSINH) AS 'SINH THU' FROM NHANVIEN;

---- CHO BIET SO LUONG NHAN VIEN, TEN TRUONG PHONG, NGAY NHAN CHUC HIEN THI THEO dd-mm-yy
SELECT * FROM PHONGBAN
SELECT * FROM NHANVIEN

DECLARE @ThongKe TABLE ( PHONG INT , SONHANVIEN INT, PHG INT)

INSERT INTO @ThongKe SELECT PHG,COUNT(MANV),PHG FROM NHANVIEN 
GROUP BY PHG

DECLARE @ThongKe2 TABLE ( TENNV NVARCHAR(15) , NG_NHANCHUC DATE, MAPHG INT )
INSERT INTO @ThongKe2 SELECT n.TENNV , p.NG_NHANCHUC, p.MAPHG
FROM NHANVIEN n
JOIN PHONGBAN p 
ON n.MANV = p.TRPHG

SELECT TK2.TENNV, 
	CONVERT (VARCHAR, TK2.NG_NHANCHUC,105) AS 'NGAY NHAN CHUC',
	TK1.SONHANVIEN -1
FROM @ThongKe2 TK2
JOIN @ThongKe TK1
ON TK1.PHG = TK2.MAPHG
---OR--
SELECT a.TRPHG, c.TENNV, a.NG_NHANCHUC, b.SL FROM PHONGBAN a
 JOIN ( SELECT PHG, COUNT(MANV) AS SL FROM NHANVIEN GROUP BY PHG) b 
ON a.MAPHG = b.PHG
 JOIN NHANVIEN c ON a.TRPHG = c.MANV
----OR---



SELECT c.TENNV, b.PHG, b.SL , a.NG_NHANCHUC FROM PHONGBAN a
INNER JOIN  (SELECT PHG, COUNT(MANV) AS SL  FROM NHANVIEN GROUP BY PHG) AS b 
ON a.MAPHG = b.PHG
INNER JOIN NHANVIEN c 
ON a.TRPHG = c.MANV	

----------------------------
--------- IF ELSE CASE ---- FOR NHAN VIEN
----------------------------
SELECT PHG, COUNT(MANV), 'TRANG THAI' = IIF(COUNT(MANV) < 3, N'THIEU NHAN VIEN',
	IIF(COUNT(MANV) <5, N'DU NHAN VIEN',N'DONG NHAN VIEN'))
FROM NHANVIEN GROUP BY PHG ;

-----TINH THUE  THEO LUONG----X
-- TU 0 DEN 25000 , THUE = 0.1* LUONG
-- TU 25000 DEN 30000 THUE = 0.12*LUONG
-- TU 30000 DEN 40000 THUE = 0.15*LUONG
-- TU 40000 DEN 50000 THUE = 0.2* LUONG
-- CON LAI, THUE = 0.25* LUONG
DECLARE @THUE FLOAT 
SELECT TENNV, LUONG,
	'THUE' = CASE 
		WHEN LUONG BETWEEN 0 AND 25000 THEN  LUONG*0.1
		WHEN LUONG BETWEEN 25000 AND 30000 THEN  LUONG*0.12
		WHEN LUONG BETWEEN 30000 AND 40000 THEN  LUONG*0.15
		WHEN LUONG BETWEEN 40000 AND 50000 THEN  LUONG*0.2
		ELSE LUONG*0.25
		END
FROM NHANVIEN

------WHILE--BREAK--CONTINUE--
---TINH TONG CAC SO CHAN 1 DEN 10

DECLARE @NUM INT, @SUM INT 
SET @NUM =1
SET @SUM =0 
WHILE @NUM <= 10
BEGIN 
	IF @NUM%2 = 0 
		SET @SUM = @SUM + @NUM
	
	SET @NUM = @NUM +1
END

PRINT 'TONG ' + CAST( @SUM AS VARCHAR)
------WHILE--BREAK--CONTINUE--
---TINH TONG CAC SO CHAN 1 DEN 10 NHUNG BO SO 4
----
DECLARE @NUM INT, @SUM INT 
SET @NUM =1
SET @SUM =0 
WHILE @NUM <= 10
BEGIN 
	IF @NUM = 4 
	BEGIN 
		SET @NUM = @NUM +1
		CONTINUE
	END;
	IF @NUM%2 = 0 
		SET @SUM = @SUM + @NUM
		 
	SET @NUM = @NUM +1
END

PRINT 'TONG ' + CAST( @SUM AS VARCHAR)
-----TRY CATCH 
------
BEGIN TRY	
	INSERT PHONGBAN
	VALUES (799,'ZXK-779', '2008-07-01','0197-05-22')
	PRINT 'SUCCESS : RECORD WAS INSERT'
END TRY
BEGIN CATCH 
	PRINT 'FAILURE: RECORD WAS NOT INSERT'
	PRINT 'ERROR' + CONVERT(VARCHAR, ERROR_NUMBER(),1)
	+ ERROR_MESSAGE()
END CATCH
-----
--RAISERROR(TBAO_LOI, MUCDOLOI, TRANG THAI LOI)
--
BEGIN TRY
	DECLARE @RESULT INT 
	SET @RESULT = 55/0
END TRY
BEGIN CATCH 
DECLARE 
	@ErMessage Nvarchar(2048),
	@ErSeverity Int,
	@ErState Int
SELECT 
	@ErMessage = ERROR_MESSAGE(),
	@ErSeverity = ERROR_SEVERITY(),
	@ErState = ERROR_STATE()
RAISERROR(@ErMessage,@ErSeverity,@ErState)
END CATCH
----
---



